In [1]:
import pandas as pd
import numpy as np

In [2]:
# assign data
df_train = pd.read_csv('Data/BPI Challenge 2012/BPI_Challenge_2012-training.csv')
df_test = pd.read_csv('Data/BPI Challenge 2012/BPI_Challenge_2012-test.csv')

In [3]:
# assign column names to variables for ease

cEvent = 'event concept:name'
cNew = 'next event'
cPred = 'predicted next event'

df_train[cPred] = np.nan
df_train[cNew] = df_train[cEvent].shift(-1)
df_train.tail()

,eventID,case concept:name,case REG_DATE,case AMOUNT_REQ,event concept:name,event lifecycle:transition,event time:timestamp,predicted next event,next event
214372,38835094290529,201854,2012-01-18T02:09:07.029+01:00,50000,O_CANCELLED,COMPLETE,14-03-2012 15:30:19.361,NaN,A_CANCELLED
214373,38835094290528,201854,2012-01-18T02:09:07.029+01:00,50000,A_CANCELLED,COMPLETE,14-03-2012 15:30:19.361,NaN,W_Nabellen incomplete dossiers
214374,38835094290530,201854,2012-01-18T02:09:07.029+01:00,50000,W_Nabellen incomplete dossiers,COMPLETE,14-03-2012 15:30:23.187,NaN,W_Nabellen offertes
214375,35858681954366,199678,2012-01-10T19:16:52.800+01:00,30000,W_Nabellen offertes,START,14-03-2012 15:36:15.299,NaN,W_Nabellen offertes
214376,35858681954367,199678,2012-01-10T19:16:52.800+01:00,30000,W_Nabellen offertes,COMPLETE,14-03-2012 15:40:34.231,NaN,NaN

In [4]:
# create list of all possible events and display if correct

lstEvents = df_train[cEvent].unique().tolist()
lstEvents

['A_SUBMITTED',
 'A_PARTLYSUBMITTED',
 'A_PREACCEPTED',
 'W_Completeren aanvraag',
 'A_DECLINED',
 'W_Afhandelen leads',
 'A_ACCEPTED',
 'O_SELECTED',
 'A_FINALIZED',
 'O_CREATED',
 'O_SENT',
 'W_Nabellen offertes',
 'O_CANCELLED',
 'A_CANCELLED',
 'W_Beoordelen fraude',
 'O_SENT_BACK',
 'W_Valideren aanvraag',
 'W_Nabellen incomplete dossiers',
 'O_ACCEPTED',
 'A_APPROVED',
 'A_ACTIVATED',
 'A_REGISTERED',
 'O_DECLINED',
 'W_Wijzigen contractgegevens']

In [5]:
# helper function
def simple_pred(df, lst, cEvnt, cPrd, cNw):
    '''loops through the list of events and adds them to the df'''
    i = 0
    while i < len(lst):
        df.loc[df[cEvnt] == lst[i], cPrd] = df[df[cEvnt] == lst[i]][cNw].mode()[0]
        i += 1
    return df

In [6]:
# assign prediction
simple_pred(df_train, lstEvents, cEvent, cPred, cNew)

,eventID,case concept:name,case REG_DATE,case AMOUNT_REQ,event concept:name,event lifecycle:transition,event time:timestamp,predicted next event,next event
0,0,173688,2011-10-01T00:38:44.546+02:00,20000,A_SUBMITTED,COMPLETE,01-10-2011 00:38:44.546,A_PARTLYSUBMITTED,A_PARTLYSUBMITTED
1,1,173688,2011-10-01T00:38:44.546+02:00,20000,A_PARTLYSUBMITTED,COMPLETE,01-10-2011 00:38:44.880,W_Afhandelen leads,A_PREACCEPTED
2,2,173688,2011-10-01T00:38:44.546+02:00,20000,A_PREACCEPTED,COMPLETE,01-10-2011 00:39:37.906,W_Completeren aanvraag,W_Completeren aanvraag
3,3,173688,2011-10-01T00:38:44.546+02:00,20000,W_Completeren aanvraag,SCHEDULE,01-10-2011 00:39:38.875,W_Completeren aanvraag,A_SUBMITTED
4,4294967296,173691,2011-10-01T08:08:58.256+02:00,5000,A_SUBMITTED,COMPLETE,01-10-2011 08:08:58.256,A_PARTLYSUBMITTED,A_PARTLYSUBMITTED
...,...,...,...,...,...,...,...,...,...
214372,38835094290529,201854,2012-01-18T02:09:07.029+01:00,50000,O_CANCELLED,COMPLETE,14-03-2012 15:30:19.361,O_SELECTED,A_CANCELLED
214373,38835094290528,201854,2012-01-18T02:09:07.029+01:00,50000,A_CANCELLED,COMPLETE,14-03-2012 15:30:19.361,W_Completeren aanvraag,W_Nabellen incomplete dossiers
214374,38835094290530,201854,2012-01-18T02:09:07.029+01:00,50000,W_Nabellen incomplete dossiers,COMPLETE,14-03-2012 15:30:23.187,W_Nabellen incomplete dossiers,W_Nabellen offertes
214375,35858681954366,199678,2012-01-10T19:16:52.800+01:00,30000,W_Nabellen offertes,START,14-03-2012 15:36:15.299,W_Nabellen offertes,W_Nabellen offertes
214376,35858681954367,199678,2012-01-10T19:16:52.800+01:00,30000,W_Nabellen offertes,COMPLETE,14-03-2012 15:40:34.231,W_Nabellen offertes,NaN

In [7]:
# check
df_train.head()

,eventID,case concept:name,case REG_DATE,case AMOUNT_REQ,event concept:name,event lifecycle:transition,event time:timestamp,predicted next event,next event
0,0,173688,2011-10-01T00:38:44.546+02:00,20000,A_SUBMITTED,COMPLETE,01-10-2011 00:38:44.546,A_PARTLYSUBMITTED,A_PARTLYSUBMITTED
1,1,173688,2011-10-01T00:38:44.546+02:00,20000,A_PARTLYSUBMITTED,COMPLETE,01-10-2011 00:38:44.880,W_Afhandelen leads,A_PREACCEPTED
2,2,173688,2011-10-01T00:38:44.546+02:00,20000,A_PREACCEPTED,COMPLETE,01-10-2011 00:39:37.906,W_Completeren aanvraag,W_Completeren aanvraag
3,3,173688,2011-10-01T00:38:44.546+02:00,20000,W_Completeren aanvraag,SCHEDULE,01-10-2011 00:39:38.875,W_Completeren aanvraag,A_SUBMITTED
4,4294967296,173691,2011-10-01T08:08:58.256+02:00,5000,A_SUBMITTED,COMPLETE,01-10-2011 08:08:58.256,A_PARTLYSUBMITTED,A_PARTLYSUBMITTED